#左から秒(0-59)、分(0-59)、時(0-23)、日(1-31)、月(1-12)、曜日(0:日,1:月,2:火,3:水,4:木,5:金,6:土,7:日)を設定する。
#0 0 * * * * 毎時、0分0秒時に実行.
#0 0 0 * * * 毎日、0時0分0秒に実行.
#0 0 0 1 * * 毎月、1日0時0分0秒に実行.
#0 0 12 */5 * *  毎月、5の倍数の日の12時0分0秒に実行.
#0 0 9-18 * * 1-5  月から金曜日の9時から18時の0分0秒時に実行.
cron:
  sweepProcess: 0 * * * * *